name: main

on:
  schedule:
    - cron: "0 0 * * *" 
    - cron: '12 0 * * *'
    - cron: '18 0 * * *'
  workflow_dispatch:      # 允许手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 添加写权限
    steps:
      - name: Commit changes
        run: git push