name: main-status

on:
  schedule:
    - cron: "0 0 * * *" 
    - cron: '12 0 * * *'
    - cron: '18 0 * * *'
  workflow_dispatch:      # 允许手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 添加写权限

    steps:
      # 1. 检出代码（关键步骤！）
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取完整提交历史（可选）

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          # 安装必要的编译工具和依赖
          sudo apt-get install -y \
            cmake \
            pkg-config \
            ruby-dev \
            build-essential \
            libicu-dev \
            zlib1g-dev

      - name: Install GitHub Linguist
        run: |
          # 使用 gem 用户安装模式（避免权限问题）
          gem install --user-install github-linguist
          # 将 gem 的二进制路径添加到环境变量
          echo "$HOME/.gem/ruby/$(ls $HOME/.gem/ruby)/bin" >> $GITHUB_PATH
      
      - name: Generate language stats
        id: stats
        run: |
          linguist --json > linguist.json
          echo "stats=$(cat linguist.json)" >> $GITHUB_OUTPUT

      # 2. 生成或修改文件（例如更新 README）
      - name: Generate/Update README
        run: |
          echo "Last updated: $(date)" >> README.md

      # 3. 提交更改
      - name: Commit changes
        run: |
          git config --global user.name "666-arch"
          git config --global user.email "hc18174419502@163.com"
          git add README.md
          git commit -m "Auto-update README"

      # 4. 推送到远程仓库
      - name: Push changes
        run: git push