name: Update README

on:
  schedule:
    - cron: "0 0 * * *"  # 每天运行一次
  workflow_dispatch:      # 允许手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 添加写权限
    steps:
      - name: Commit changes
        run: git push